[ADD] 2주차 타이머 과제
mingking2/FE-React-Study pull request #12
Opened 2023-07-20 09:44 UTC by sangjung0

2023-07-23 07:10 UTC, whitecity01 commented on week2/sangjung/TimerApp.js
> +TimerApp.propTypes = {
코드 리뷰: 김승제
1. TimerApp 내부에서 사용된 state에 대해 propTypes를 검사할 필요 없어 보임

2023-07-23 07:10 UTC, whitecity01 commented on week2/sangjung/Timer.js
> +    const setTimerIsRunning = (bool) => {
코드 리뷰: 김승제
1. setTimerIsRunning <= 중복되는 변수 이름으로 읽는데 너무 헷갈림(내 기준 ㅠ)

2023-07-23 07:14 UTC, sangjung0 commented on week2/sangjung/Timer.js
> +    const setTimerIsRunning = (bool) => {
맞는말..ㅠ 적당한 변수명을 찾지 못함

2023-07-23 12:57 UTC, BangDori requested changes
코드 리뷰 확인하고 수정해주세용

2023-07-23 12:57 UTC, BangDori commented on week2/sangjung/Timer.js
> +    const [timerIsRunning, _setTimerIsRunning] = useState(false);
1. `timerIsRunning` -> `isRunning` 수정하는게 가독성 측면에서 좋음
2. 아래 `setTimerIsRunning` 함수와, `_setTimerIsRunning` 함수 네이밍이 동일한데, `useState`로 받아오는 경우에는 무조건 `[name, setName]` 으로 고정하는게 좋음

2023-07-23 12:57 UTC, BangDori commented on week2/sangjung/Timer.js
> +    const timerAction = useRef();
`timerAction`이라는 `ref`를 `TimerDisplay` 컴포넌트에 전달하고 있는데, `ref`는 일반적으로 리액트 컴포넌트가 아닌, DOM 요소에 접근하기 위한 용도로 사용됩니다. (리액트 컴포넌트에 `ref`를 설정하면 `ref`가 정상적으로 동작되지 않는 문제가 발생할 수 있기 때문에, DOM 요소에 전달해주는 것이 좋습니다.)

2023-07-23 12:57 UTC, BangDori commented on week2/sangjung/Timer.js
> +                    </ButtonGroup>
onClick 이벤트 핸들러들이 각각 익명 함수를 생성하여 매번 새로운 함수를 할당하는 것으로, 성능상 약간의 오버헤드가 발생할 수 있습니다. 그렇기 때문에 onClick 이벤트 핸들러를 클래스 내부의 메서드로 정의하고 사용하는 것이 성능 및 가독성 측면에서 더 좋은 방법입니다.

2023-07-23 12:57 UTC, BangDori commented on week2/sangjung/TimerAction.js
TimerAction 컴포넌트의 역할이 코드에서 명확하게 드러나지 않습니다. 컴포넌트의 이름과 역할을 주석을 통해 명확하게 설명하는 것이 좋습니다.

2023-07-23 12:57 UTC, BangDori commented on week2/sangjung/TimerApp.js
> +        const timerBox = document.querySelector(".timer-box");
document.querySelector를 통해 DOM을 직접 조작하고 있는데, 리액트에서 DOM을 직접하는 행위는 피하는 것이 좋습니다.

2023-07-23 12:57 UTC, BangDori commented on week2/sangjung/TimerApp.js
> +    },[]);
`window.addEventListener('resize',handleResize);` 다음과 같이 이벤트리스너를 추가해주었다면, 클린업 함수로 언마운트되는 상황에서 이벤트리스너를 제거해주는 것이 메모리 관리에 도움이 됩니다.

2023-07-23 12:57 UTC, BangDori commented on week2/sangjung/TimerDisplay.js
> +    const [timer,setTimer] = useState();
초기값을 설정하지 않아, timer 상태 변수가 무엇을 나타내는 변수인지 추측하기 어려움

2023-07-23 12:57 UTC, BangDori commented on week2/sangjung/TimerDisplay.js
> +    const [error, setError] = useState(false);
`error` -> `isError` 가독성 향상

2023-07-23 12:57 UTC, BangDori commented on week2/sangjung/TimerDisplay.js
> +    const startTimer = () =>{
너무 복잡한 코드는, 예기치 못한 결과를 초래할 수 있습니다.

2023-07-26 05:39 UTC, BangDori reviewed
고생하셨습니당 ~

2023-07-26 05:40 UTC, merged