Chore: Week2 completed
mingking2/FE-React-Study pull request #17
Opened 2023-07-22 11:25 UTC by Tentennball

최은성과 피드백 완료(useEffect부분 hours처리 추가, 에러처리 수정, JSX 수정)

2023-07-23 13:09 UTC, BangDori requested changes
변수가 너무 많고, 컴포넌트의 분리가 명확하게 이뤄지지 않은 것 같습니다.

2023-07-23 15:02 UTC, Tentennball commented
display를 없앨 방법이 떠오르지않ㅇㅏ요...

2023-07-23 15:21 UTC, BangDori requested changes
리뷰 확인 후 수정바랍니다~

2023-07-23 15:21 UTC, BangDori commented on week2/taehoon/src/Timer.js
> +        </TimerDisplay>
`display: none`으로 안 보이게 하더라도, 컴포넌트 자체는 그 자리를 차지하기 때문에 그만큼의 무게를 가지게 됩니다. 그렇기 때문에 style 속성으로 안보이게 하는 것이 아니라, isRunning의 True/False에 따라 Input과 TimerDisplay 컴포넌트를 로드할지 안할지는 결정하는 것이 더 좋을 것 같습니다.

2023-07-23 15:21 UTC, BangDori commented on week2/taehoon/src/Timer.js
> +  const [display, setDisplay] = useState(false);
`isRunning`으로 Input, TimerDisplay를 번갈아서 보여줄 수 있으므로 display 변수를 선언하지 않아도 될 것 같습니다.

2023-07-24 16:02 UTC, BangDori reviewed
문제가 발생할 수 있는 코드를 작성하는 것은 잘못된 것이 아니에요. 하지만 해당 코드에 문제가 있는 것을 알고도 수정하지 않는 것은 잘못된 것이라고 생각해요.

문제가 발생할 수 있는 코드를 수정해나감으로써 코드에 대한 이해도가 더욱 깊어지고, 더 깊이있는 개발자로 거듭날 수 있을거라고 전 생각해요.

그래서 시간이 있다면 꼭 문제가 발생할 수 있는 부분에 대해 깊이 고민해 보시고, 코드를 수정해서 다시 PR 해보시는걸 추천합니다!!

2023-07-24 16:04 UTC, merged